{% set name = "fiatlux" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fiatlux-{{ version }}.tar.gz
  sha256: 104fd05f8543bb21281edcbac531aca30b52bfea5ddaf9e449f28fd595b32066

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - make
    - cmake >=3.15
  host:
    - python
    - pip
    - pybind11 >=2.6.0
    - scikit-build
  run:
    - python

test:
  imports:
    - fiatlux
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scarrazza/fiatlux/
  summary: API for LUXqed methodology in global PDF fits
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarlehoff
    - scarrazza
