{% set name = "fiatlux" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fiatlux-{{ version }}.tar.gz
  sha256: de0166c220044a0c004e72e294f750e7d0255fd3ab46db0fe84dd1a259dae0e1

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - {{ stdlib("c") }}
    - make
    - cmake >=3.15
  host:
    - python
    - pip
    - pybind11 >=2.6.0
    - scikit-build
  run:
    - python

test:
  imports:
    - fiatlux
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scarrazza/fiatlux/
  summary: API for LUXqed methodology in global PDF fits
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarlehoff
    - scarrazza
